# Generated by Django 4.0.5 on 2022-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_cryptopayment_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopayment',
            name='transaction_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shaparakpayment',
            name='transaction_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
