# Generated by Django 4.0.5 on 2022-06-17 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libgen_id', models.IntegerField(default=-1, unique=True)),
                ('title', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=5000)),
                ('description', models.TextField(blank=True, null=True)),
                ('series', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, max_length=300, null=True)),
                ('edition', models.TextField(blank=True)),
                ('pages', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('English', 'en'), ('Russian', 'ru'), ('French', 'fr'), ('Spanish', 'es'), ('German', 'de'), ('Italian', 'it')], default='English', max_length=50)),
                ('topic', models.TextField(default='Other')),
                ('cover_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('cover', models.ImageField(blank=True, max_length=5000, null=True, upload_to='covers')),
                ('identifier', models.TextField(blank=True)),
                ('md5', models.CharField(blank=True, max_length=300)),
                ('filesize', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('extension', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB'), ('djvu', 'DJVU'), ('doc', 'DOC'), ('mobi', 'MOBI'), ('rar', 'RAR'), ('zip', 'ZIP'), ('azw3', 'AZW3')], default='pdf', max_length=50)),
                ('download_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['libgen_id'], name='store_book_libgen__611373_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='store_book_title_579c41_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='store_book_slug_22f0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['identifier'], name='store_book_identif_b665cb_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['authors'], name='store_book_authors_86dc29_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publisher'], name='store_book_publish_58c024_idx'),
        ),
    ]
