# Generated by Django 4.0.5 on 2022-06-17 07:55

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_document'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(fields=['document'], name='store_book_documen_844838_gin'),
        ),
    ]
