# Generated by Django 4.0.5 on 2022-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_store_book_documen_844838_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
