# Generated by Django 4.0.5 on 2022-06-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_telegrambook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramBook',
        ),
    ]
