# Generated by Django 4.0.5 on 2022-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_telegrambook'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['md5'], name='store_book_md5_a483f4_idx'),
        ),
    ]
