# Generated by Django 4.0.5 on 2022-06-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZlibAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(max_length=20)),
                ('user_key', models.CharField(max_length=50)),
            ],
        ),
    ]
