# Generated by Django 4.0.5 on 2022-06-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlibaccount',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
