# Generated by Django 4.0.5 on 2022-06-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_zlibaccount_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zlibaccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='zlibaccount',
            name='password',
        ),
    ]
